<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>[+ 의사 정보 등록]</description>
   <name>btn_doctor_add</name>
   <tag></tag>
   <elementGuidId>508a6db7-bc75-430d-bb0c-cbf0ca47cf35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-layout-container/div[2]/app-hospital-info-doctors-page/div/app-card-guide/article/section/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea27c41f-acd2-4d32-8118-e3a409608962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-layout-container/div[2]/app-hospital-info-doctors-page/div/app-card-guide/article/section/button</value>
      <webElementGuid>a6df8ac5-f624-47f0-aad4-3f6262102be5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
