<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>점심시간</description>
   <name>txt_lunch</name>
   <tag></tag>
   <elementGuidId>cd8a64b8-d102-43db-949f-7c8c70a1d9e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-layout-container/div[2]/app-hospital-info-schedule-page/app-operating-time-list/div/div/div[2]/app-card-time-table[2]/div/div[2]/table/tr[1]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-layout-container/div[2]/app-hospital-info-schedule-page/app-operating-time-list/div/div/div[2]/app-card-time-table[2]/div/div[2]/table/tr[1]/td</value>
      <webElementGuid>82644d70-1d3e-4e23-ac39-cb2d5e164865</webElementGuid>
   </webElementProperties>
</WebElementEntity>
