<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>병원소개</description>
   <name>txt_hospital_note</name>
   <tag></tag>
   <elementGuidId>44e2733e-4cb8-4741-a389-6226886caf5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;hospitalNote&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;hospitalNote&quot;]</value>
      <webElementGuid>b45bab52-d005-4752-ab51-fea68255aede</webElementGuid>
   </webElementProperties>
</WebElementEntity>
